@Address = https://localhost:7263

POST {{Address}}/api/auth/register
Content-Type: application/json

{
  "FirstName": "Test",
  "LastName": "Test",
  "UserName": "test123",
  "Email": "test@gmail.com",
  "Password": "test123",
  "ConfirmPassword": "test123"
}